repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0  # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]   # Replace with Django version
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
        files: \.(js|scss)$
        exclude_types: [html]
        additional_dependencies:
          - prettier@2.8.1 # Required because pre-commit is poorly maintained
