# Generated by Django 1.10 on 2016-08-25 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openach", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("NA", "N/A"),
                            ("VI", "Very Inconsistent"),
                            ("I", "Inconsistent"),
                            ("N", "Neutral"),
                            ("C", "Consistent"),
                            ("VC", "Very Consistent"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="evidence_desc",
            field=models.CharField(
                default="This evidence needs a description", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hypothesis",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="openach.Board"
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="openach.Evidence"
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="hypothesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="openach.Hypothesis"
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
