# Generated by Django 1.10 on 2016-08-26 17:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openach", "0005_evidencesource_source_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="submit_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2016, 8, 26, 17, 29, 46, 660576, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date added",
            ),
            preserve_default=False,
        ),
    ]
