# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0007_auto_20160826_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='event_date',
            field=models.DateField(null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='evidencesourcetag',
            name='tag_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
