# Generated by Django 1.10 on 2016-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0009_projectnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencesource",
            name="corroborating",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
