# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0011_board_board_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_slug",
            field=models.SlugField(max_length=72, null=True),
        ),
    ]
