# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 03:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0012_auto_20160829_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypothesis',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 3, 5, 15, 430181, tzinfo=utc), verbose_name='date added'),
            preserve_default=False,
        ),
    ]
