# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0015_auto_20160915_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesource',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
