# Generated by Django 1.10.1 on 2016-09-23 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0018_auto_20160919_2318"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardFollower",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_creator", models.BooleanField(default=False)),
                ("is_contributor", models.BooleanField(default=False)),
                ("is_evaluator", models.BooleanField(default=False)),
                ("update_timestamp", models.DateTimeField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="openach.Board",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="openach.Board"
                    ),
                ),
            ],
        ),
    ]
