# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 01:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0019_boardfollower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardfollower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
