# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0021_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="digest_frequency",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Never"), (1, "Daily"), (2, "Weekly")],
                default=1,
                verbose_name="email digest frequency",
            ),
        ),
    ]
