# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 03:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0028_initusersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analystsourcetag",
            name="tag_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date tagged"),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_desc",
            field=models.CharField(
                help_text="A description providing context around the topic. Helps to clarify which hypotheses and evidence are relevant",
                max_length=255,
                verbose_name="board description",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_slug",
            field=models.SlugField(editable=False, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_title",
            field=models.CharField(
                help_text="The board title. Typically phrased as a question asking about what happened in the past, what is happening currently, or what will happen in the future",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="boardfollower",
            name="update_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="date evaluated"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="event_date",
            field=models.DateField(
                help_text="The date the event occurred or started",
                null=True,
                verbose_name="evidence event date",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="evidence_desc",
            field=models.CharField(
                help_text="A short summary of the evidence. Use the event date field for capturing the date",
                max_length=200,
                verbose_name="evidence description",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="submit_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="evidencesource",
            name="source_date",
            field=models.DateField(
                help_text="The date the source released or last updated the information corroborating the evidence. Typically the date of the article or post",
                verbose_name="source date",
            ),
        ),
        migrations.AlterField(
            model_name="evidencesource",
            name="source_url",
            field=models.URLField(
                help_text="A source (e.g., news article or press release) corroborating the evidence",
                max_length=255,
                verbose_name="source website",
            ),
        ),
        migrations.AlterField(
            model_name="evidencesource",
            name="submit_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="hypothesis",
            name="submit_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="digest_frequency",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Never"), (1, "Daily"), (2, "Weekly")],
                default=1,
                help_text="How frequently to receive email updates containing notifications you've missed.",
                verbose_name="email digest frequency",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
