# Generated by Django 1.10.2 on 2016-10-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0031_auto_20161004_1651"),
        ("openach", "0030_auto_20161008_1249"),
    ]

    operations = []
