# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0032_auto_20161010_1940'),
        ('openach', '0033_auto_20161020_1844'),
    ]

    operations = [
    ]
