# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openach', '0034_merge_20161021_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_board', models.PositiveSmallIntegerField(choices=[(0, 'Only Me'), (1, 'Collaborators'), (2, 'Registered Users'), (3, 'Public')], default=1, help_text='Who can view the board?')),
                ('read_comments', models.PositiveSmallIntegerField(choices=[(0, 'Only Me'), (1, 'Collaborators'), (2, 'Registered Users'), (3, 'Public')], default=1, help_text='Who can view board comments?')),
                ('add_comments', models.PositiveSmallIntegerField(choices=[(0, 'Only Me'), (1, 'Collaborators'), (2, 'Registered Users'), (3, 'Public')], default=1, help_text='Who can commment on the board?')),
                ('add_elements', models.PositiveSmallIntegerField(choices=[(0, 'Only Me'), (1, 'Collaborators'), (2, 'Registered Users'), (3, 'Public')], default=1, help_text='Who can add hypotheses, evidence, and sources?')),
                ('edit_elements', models.PositiveSmallIntegerField(choices=[(0, 'Only Me'), (1, 'Collaborators'), (2, 'Registered Users'), (3, 'Public')], default=1, help_text='Who can edit hypotheses and evidence that they did not add?')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='openach.Board')),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
