# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openach', '0042_auto_20180113_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='public',
            field=models.BooleanField(default=True, help_text='Whether or not the team is visible to non-members'),
        ),
    ]
