# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openach", "0043_auto_20180113_0323"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamrequest", unique_together=set([("team", "inviter", "invitee")]),
        ),
    ]
