# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0044_auto_20180325_0211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="event_date",
            field=models.DateField(
                blank=True,
                help_text="The date the event occurred or started",
                null=True,
                verbose_name="evidence event date",
            ),
        ),
    ]
