# Generated by Django 3.2.6 on 2021-08-21 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openach", "0046_auto_20180908_0056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_title",
            field=models.CharField(
                db_index=True,
                help_text="The board title. Typically phrased as a question asking about what happened in the past, what is happening currently, or what will happen in the future",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((?![!@#^*~`|<>{}+=\\[\\]]).)*$",
                        "No special characters allowed.",
                    )
                ],
            ),
        ),
    ]
