# Generated by Django 4.2.10 on 2024-03-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openach', '0047_alter_board_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='invites_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('invites_remaining', models.IntegerField(default=0)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
